version: '3.7'



services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - '3000:3000'
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
      REDIS_URL: redis://cache
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.9.45
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      driver: default

    

volumes:
  data:
    driver: local
